POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Hackr",
    "author": "Community",
    "url": "https://hackr.io/blog",
    "likes": 0
}

###
GET http://localhost:3001/api/blogs

###
DELETE  http://localhost:3001/api/blogs/64bc2f6d2b6f64b794a42b27